name: byui_rideshare
description: "Rideshare App for BYU-Idaho"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.11
  add_2_calendar: ^3.0.1

  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.0
  firebase_messaging: ^15.1.0
  firebase_storage: ^12.4.7
  flutter_local_notifications:
    git:
      url: https://github.com/MaikuB/flutter_local_notifications.git
      ref: master
      path: flutter_local_notifications
  cloud_firestore: ^5.6.9
  intl: ^0.20.2
  google_sign_in: ^6.1.5
  image_picker: ^1.1.2
  mask_text_input_formatter: ^2.3.0 # For making the phone number appear with dashes
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^10.7.0

  flutter_lints: ^5.0.0

flutter:

  assets:
    - assets/images/

  uses-material-design: true

