name: byui_rideshare
description: "Rideshare App for BYU-Idaho"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.11

  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.0 # Required for all Firebase products
  firebase_auth: ^4.17.8 # For email/password and other auth methods
  cloud_firestore: ^4.15.8 # For the Firestore database
  intl: ^0.18.0
  google_sign_in: ^6.2.1
  mask_text_input_formatter: ^2.3.0 # For making the phone number appear with dashes

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^10.7.0

  flutter_lints: ^5.0.0

flutter:

  assets:
    - assets/images/

  uses-material-design: true

