import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Import Firebase Core
import 'firebase_options.dart'; // Import Firebase options

// Keep your import for the login page
import 'package:byui_rideshare/screens/auth/login_page.dart'; // Assuming this is the correct path

// This is the main entry point of your application.
// It's made asynchronous because initializing Firebase is an async operation.
void main() async {
  // Ensure that the Flutter binding to the native platform is initialized.
  // This is necessary before calling any methods that interact with the native (platform) side,
  // which Firebase.initializeApp() does.
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with the default options for the current platform (Android/iOS/Web etc.).
  // The configuration for these options comes from the firebase_options.dart file generated by flutterfire configure.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // After Firebase is successfully initialized, run your main application widget.
  runApp(const MyApp());
}

// This is the root widget of your application.
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'BYU-I Rideshare', // Your app title
      theme: ThemeData(
        // This is the theme of your application.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true, // Recommended for modern Material Design
      ),

      // created routes so we can return to the homepage...
      initialRoute: '/', // Starting screen
      routes: {
        '/': (context) => const MyHomePage(title: 'BYU-I Rideshare'),
        '/login': (context) => const LoginPage(),
      },

      // Set the home page to your welcome screen
      // home: const MyHomePage(title: 'BYU-I Rideshare'),
    );
  }
}

// This widget represents your welcome page. It is stateful because it might
// need to manage state in the future (though currently stateless for navigation).
class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    // This method builds the UI for your welcome page.
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center( // Center the content on the page
        child: Column( // Arrange widgets vertically
          mainAxisSize: MainAxisSize.min, // Keep the column compact
          children: [
            Text(
              'Welcome to BYU-I Rideshare!', // Your welcome message
              style: TextStyle(fontSize: 20),
            ),
            SizedBox(height: 20), // Add vertical spacing
            ElevatedButton( // Your button to navigate to login
              onPressed: () {
                // Use Navigator.push to go to the LoginPage
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => const LoginPage()),
                );
              },
              child: Text('Login here'),
            ),
          ],
        ),
      ),
    );
  }
}