name: Flutter CI/CD

on:
  push:
    branches:
      - release

jobs:
  build-test:
    name: Test & Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Run Formatter Check
        run: flutter format --set-exit-if-changed .

      - name: Run Static Analysis
        run: flutter analyze

      - name: Run Unit & Widget Tests
        run: flutter test


  deploy:
    name: Deploy to Firebase
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js (for Firebase Functions)
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Match your Firebase Functions Node version

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Install Node Dependencies for Functions
        working-directory: functions
        run: npm ci

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --only functions,hosting

      - name: Notify Slack of Deployment
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ Deployment to Firebase and Stores completed successfully!"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
